# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java build with Maven

on: 
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!main'
      - '!master'

#  pull_request:
#    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      run: mvn -B clean install --file pom.xml -s ci_settings.xml
      env:
          maven_access_user: ${{ secrets.SVC_GITHUB_USER }}
          maven_access_token: ${{ secrets.GITHUB_TOKEN }}
